### ISSUE TITLE
Cleanup after PR review for Momentum 3-block NMD

### ISSUE THREAD

**Issue by sfohr** [flatironinstitute/nomad#19]
**Which of these best describes your feature request:**
- [x] Library usability improvement
- [ ] Performance improvement (speed, accuracy)
- [ ] New methodology or algorithm

As discussed in the code review for pull request #16 this issue adresses the straightforward improvements (sorry, I'm deviating from the template as the changes are rather minor):

**0. I forgot the most obvious: updating `README.md`**

**1. In `model_free_util.py`**
- change docstring at the top "Utility functions for base model-free kernels. ~~Most likely will not be expanded, even as other
naive kernels are added.~~" ([comment](https://github.com/flatironinstitute/nomad/pull/16#discussion_r1539706694))
- typo in docstring for `apply_momentum` ([comment](https://github.com/flatironinstitute/nomad/pull/16#discussion_r1539707360)): 
`post_momentum_X = apply_momentum(X, X_previous, beta=1.0)`
should be 
`post_momentum_X = apply_momentum(X, X_previous, beta=0.0)`

**2. In `test_factory_util.py`** ([comment](https://github.com/flatironinstitute/nomad/pull/16#discussion_r1539717221)):
- in `test_instantiate_kernel_honors_strategy_selection` test instantiating the kernel with `KernelStrategy.MOMENTUM_3_BLOCK_MODEL_FREE`

**3. In `test_model_free_util.py` add following cases to `test_apply_momentum`** ([comment](https://github.com/flatironinstitute/nomad/pull/16#discussion_r1539722939)):
- For `beta=1.0`
```beta = 1.0
result = apply_momentum(current_matrix, previous_matrix, beta)
np.testing.assert_array_equal(result - current_matrix, 2 * (current_matrix - previous_matrix))
```
- For `beta=0.0`
```beta = 0.0
result = apply_momentum(current_matrix, previous_matrix, beta)
assert_array_equal(result, current)
```

**4. In `test_momentum_three_block_model_free_kernel.py`** ([comment](https://github.com/flatironinstitute/nomad/pull/16#discussion_r1539877111)):
- separate tests for the case that `W0`or `H0` is given but not both (similar to `test_momentum_3block_model_free_kernel_W0H0_initialized_if_not_given`)

**5. Repetition of `kernel.running_report` and `kernel.report`** ([comment](https://github.com/flatironinstitute/nomad/pull/16#discussion_r1539877111))
- I'll address this in a separate issue as it might benefit from further discussion (will link the issue)

**6. In `decomposition_util.py`** ([comment](https://github.com/flatironinstitute/nomad/pull/16#discussion_r1539703135)):
- merge `two_part_factor_known_rank` and `two_part_factor`
- make the `rank` parameter `Optional[int]` and then just compute it using `np.linalg.matrix_rank` if it is `None`/not defined
- addressed in #17

**Comment by jsoules** [comment]
All looks good--thanks!

**Comment by sfohr** [comment]
Small change for 3. with `beta=1.0` (doubles the 'step' taken from previous to the current iteration):

Instead of expected result being `result - current_matrix`:

```python
result = apply_momentum(current_matrix, previous_matrix, beta)
np.testing.assert_array_equal(result - current_matrix, 2 * (current_matrix - previous_matrix))
```

it should be `result - previous_matrix`:

```python
result = apply_momentum(current_matrix, previous_matrix, beta)
np.testing.assert_array_equal(result - previous_matrix, 2 * (current_matrix - previous_matrix))
```
